# Generated by Django 4.0.3 on 2022-05-07 15:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('resnet50', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resnet50result',
            name='latency',
        ),
    ]
