# Generated by Django 4.0.3 on 2022-05-07 15:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('resnet50', '0002_remove_resnet50result_latency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resnet50result',
            old_name='test_acc',
            new_name='test_err',
        ),
        migrations.RenameField(
            model_name='resnet50result',
            old_name='valid_acc',
            new_name='valid_err',
        ),
    ]
