# Generated by Django 3.2.12 on 2022-03-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('nasbench201', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nasbench201result',
            name='res12',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='nasbench201result',
            name='res200',
            field=models.JSONField(default=dict),
        ),
    ]
