# Generated by Django 4.0.3 on 2022-04-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('nasbench201', '0002_auto_20220320_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='nasbench201result',
            name='hw_info',
            field=models.JSONField(default=dict),
        ),
    ]
