# Generated by Django 4.0.4 on 2022-04-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('nasbench201', '0003_nasbench201result_hw_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='nasbench201result',
            name='more_info',
            field=models.JSONField(default=dict),
        ),
    ]
